<?php
$__u_type 	= 'Tipologia cliente';
$__normal 	= 'Privato';
$__ditta 	= 'Azienda';
$__piva 	= 'Partita IVA';
$__soc 		= 'Societ&agrave;';
$__nation 	= 'Nazione';
$__nations	= array(
	'IT'=> 'Italia',
	'AT'=> 'Austria',
	'BE'=> 'Belgium',
	'BG'=> 'Bulgaria',
	'CY'=> 'Cyprus',
	'CZ'=> 'Czech Republic',
	'DK'=> 'Denmark',
	'EE'=> 'Estonia',
	'FI'=> 'Finland',
	'FR'=> 'France',
	'DE'=> 'Germany',
	'EL'=> 'Greece',
	'HU'=> 'Hungary',
	'IE'=> 'Ireland',
	'LV'=> 'Latvia',
	'LT'=> 'Lithuania',
	'LU'=> 'Luxembourg',
	'MT'=> 'Malta',
	'NL'=> 'Netherlands',
	'PL'=> 'Poland',
	'PT'=> 'Portugal',
	'RO'=> 'Romania',
	'SK'=> 'Slovakia',
	'SI'=> 'Slovenia',
	'ES'=> 'Spain',
	'SE'=> 'Sweden',
	'UK'=> 'United Kingdom',
	'NE'=> 'Non Europeo');
$__nc_soc_short	= 'Nome della societ&agrave; troppo corto';
$__nc_piva_err	= 'Partita IVA non valida';
?>