<?php
	$req = array(
		'version' => 'PHP Version >= 5.1',
		'rglobals' => 'Register Globals OFF',
		'zlib' => 'Zlib Compression Support',
		'db' => 'Database Support: (mysql, mysqli)',
		'json' => 'JSON Support',
		'write' => 'config/ and cache/ writables',
		'http' => 'Curl or allow_url_fopen enabled',
		'output' => 'Output Buffering'
	);
	$__req = 'Requirements';
	$__req_d = 'To install ALExxia all requirements listed here must be indicated by an YES, if some condition is referred as NO please correct it to begin the installation';
	$rac = array(
		'magic' => 'Magic Quotes GPC OFF',
		'safe' => 'Safe Mode OFF',
		'error' => 'Display Errors OFF',
		'upload' => 'Upload Files',
		'double' => 'Double database support'
	);
	$__rac = 'Recommended Settings';
	$__rac_d = 'These settings are recommended, however ALExxia is able to function well.';
	$__y = 'Yes';
	$__n = 'No';
	$__lang_sel = 'Select Language';
	$__continue = 'Next';
	$__configuration = 'General Configuration';
	$__site_with = 'My new web-site with ALExxia';
	$__name = 'Site Name';
	$__name_d = 'Enter the name of your site';
	$__desc = 'Description';
	$__desc_d = 'Enter a description of the site that will be used by the search engines. Generally, optimal is a maximum of 20 words.';
	$__email = 'Founder Email';
	$__email_d = 'Please enter your email address, this will be the email address of the founder of the site.';
	$__nick = 'Founder Nick';
	$__nick_d = 'You can change the nickname of the founder, is normally <b>admin</b>';
	$__pass = 'Founder Password';
	$__pass_d = 'Set the password of the founder of the site and confirm it in the field below';
	$__pass2 = 'Confirm Password';
	$__not_nick = 'The nickname must be at least 4 alphanumeric characters';
	$__not_pass = 'The password must be at least 6 characters';
	$__not_pass2 = 'The password confirmation does not match';
	$__not_email = 'Invalid Email';
	$__not_sname = 'The site name is too short';
	$__prev = 'Back';
	$__database = 'Database Configuration';
	$__dbt = 'Database Type';
	$__dbt_d = 'MySQLi risulta pi&ugrave; veloce di MySQL.<br/>SQLite e SQLite3 son database memorizzati su file locali.';
	$__host = 'Host Name';
	$__host_d = 'Usually is localhost';
	$__dbuser = 'Username';
	$__dbuser_d = 'Usually is root';
	$__dbpass = 'Password';
	$__dbpass_d = 'Password to access the database';
	$__dbname = 'Database Name';
	$__dbname_d = 'Name of the database in which to install ALExxia, this database will be used for the storage of the extensions and users of the site';
	$__dbpref = 'Prefix Database';
	$__dbpref_d = 'If you are not available to more than one database you can use a prefix to install more than one site with Alexxia';
	$__db2 = 'Secondary database';
	$__db2_d = 'If all you have more than one database by filling out the following fields ALExxia will use the second database for sensitive data. <br/> For a more effective security is not recommended a database accessible to the primary database';
	$__not_db = 'Unable to connect to the database, verify that the host, username and password are correct';
	$__not_dbname = 'The database name is not valid, check that you have spelled correctly and the user have permission to access';
	$__not_db2 = 'Unable to connect to the secondary database, if you do not want to use leave this field blank';
	$__not_dbname2 = 'The name of the secondary database is invalid';
	$__sum = 'Summary';
?>